"""Update Users

Revision ID: f73215b4ecd9
Revises: 734cd2c9820e
Create Date: 2026-08-18 15:48:32.556535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73215b4ecd9'
down_revision: Union[str, Sequence[str], None] = '734cd2c9820e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=True)
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###
